name: Terraform deployment

on:
  push:
    branches: ['main']
    paths: ['infrastructure/**',
            'webapp/**',
            '.github/workflows/**']

  workflow_dispatch: #this attribute will enable the manual run to the pipeline


permissions:
  contents: read

# Use the Bash shell regardless the agent OS
defaults:
  run:
    shell: bash

env:
  TERRAFORM_VERSION: 1.5.0
  TERRAFORM_REGION: ${{ vars.REGION }}
  INFRA_PATH: './infrastructure'
  WEBAPP_PATH: './webapp'
  WEB_URL: ${{ vars.WEB_URL }}

jobs:
  terraform-deploy:
    name: terraform deployment
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ env.WEB_URL }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TERRAFORM_REGION }}

      - name: Use Node.js 19.8.1
        uses: actions/setup-node@v3
        with:
          node-version: 19.8.1

      - name: Generate env variable
        run: |
          echo "${{ secrets.DOTENV_FILE }}" > .env
        working-directory: ${{ env.WEBAPP_PATH }}

      - name: Install npm dependencies
        run: npm ci
        working-directory: ${{ env.WEBAPP_PATH }}

      - name: build the react webapp
        run: npm run build
        working-directory: ${{ env.WEBAPP_PATH }}

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Init Terraform
        id: init
        run: |
          terraform init
        working-directory: ${{ env.INFRA_PATH }}

      - name: Terraform Apply
        run: |
          terraform workspace select prod
          terraform apply -auto-approve -input=false
        working-directory: ${{ env.INFRA_PATH }}
        env:
          TF_VAR_domain: ${{ vars.DOMAIN }}
